dist: bionic
language: bash
env:
  - DOKKU_VERSION=master
  - DOKKU_VERSION=v0.19.0
install: make setup
before_script: sudo sysctl -w vm.max_map_count=262144
script:
  # Check that README etc. is up to date
  - >
    make generate;
    if [[ $(git diff) ]]; then
      echo "Please run `make generate`";
      git status --short;
      git diff;
      exit 1;
    fi
  - make test
after_failure: make report
