version: 2.1

commands:
  build:
    description: "run the build"
    parameters:
      python_version:
        type: string
        default: "3.7.0"
    steps:
      - checkout

executors:
  machine:
    machine:
      docker_layer_caching: false
      image: ubuntu-1604:201903-01

jobs:
  build-master:
    environment:
      DOKKU_VERSION: master
    executor: machine
    steps:
      - build

workflows:
  version: 2
  build:
    jobs:
      - "build-master"
