#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

service-connect-admin-cmd() {
  declare desc="connect to the $PLUGIN_SERVICE service as the admin user"
  local cmd="$PLUGIN_COMMAND_PREFIX:connect-admin" argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1

  "${DOKKU_LIB_ROOT}/data/${PLUGIN_COMMAND_PREFIX}/dokku-datastore" invoke "$PLUGIN_COMMAND_PREFIX" connect-admin "$@"
}

service-connect-admin-cmd "$@"
